---
title: "R Notebook"
output: html_notebook
---
UNIVARIANT ANALYSIS



Import data 
```{r}
#data separated by commas, replace missing values with NA, use first row as headers
data <- read.csv(file = "C:/Users/16133/OneDrive/Desktop/CIND820/Data sets/PRSA_Data_Shunyi_20130301-20170228.csv", sep = ",", header = TRUE, na.strings = c("","NA"))


#check data types and first 6 rows of data
str(data)
head(data)
```
#INDIVIDUAL ANALYSIS

Complete individual analysis of each attribute (except the first and last column which just gives number and station respectively)


```{r}
#install.packages("viridis")
library("viridis")
```

#Year,Month,Day,Hour
```{r}
#check for missing values 
sum(is.na(data$year))
sum(is.na(data$month))
sum(is.na(data$day))
sum(is.na(data$hour))


#there are no missing values
```


##PM2.5
```{r}
#summary statistics
summary(data$PM2.5)

#boxplot (looking for outliers)
boxplot(data$PM2.5,ylab = "mu g/m^3")

#plot PM2.5 data against time variables
plot(data$month, data$PM2.5, col = "blue4", xlab="Months",ylab="PM2.5 (µg/m^3)",main="PM2.5 concentrations by Month")
plot(data$hour, data$PM2.5, col="blue4", xlab="Hour",ylab="PM2.5 (µg/m^3)",main="PM2.5 concentrations over the Hours")
plot(data$year, data$PM2.5, col="blue4", xlab="Year", ylab="PM2.5 (µg/m^3)", main="PM2.5 concentration each year")


PM2.5 <- data$PM2.5

#create a histogram to visualize frequency of values
hist(PM2.5, breaks = sqrt(nrow(data)), xlab = "PM2.5 (µg/m^3)", main = "Frequency Distribution of PM2.5 Concentration" , col=viridis(sqrt(nrow(data))))





```
##PM10
```{r}
#summary stats
summary(data$PM10)

#looking at outliers
boxplot(data$PM10,ylab = "mu g/m^3")

#plot values against time variables
plot(data$month, data$PM10, col="blue4", xlab="Months",ylab="PM10 (µg/m^3)",main="PM10 concentrations by Month")
plot(data$hour, data$PM10, col="blue4", xlab="Hour",ylab="PM10 (µg/m^3)",main="PM10 concentrations over the Hours")
plot(data$year, data$PM10, col="blue4", xlab="Year", ylab="PM10 (µg/m^3)", main="PM10 concentration each year")

#check distribution of values 
hist(data$PM10, breaks = sqrt(nrow(data)), xlab="PM10 (µg/m^3)", main = "Frequency Distribution of PM10 Concentration" , col=viridis(sqrt(nrow(data))))

```
##SO2
```{r}
#summary stats 
summary(data$SO2)
#outliers
boxplot(data$SO2,ylab = "mu g/m^3")
#plot values against time variables
plot(data$month, data$SO2, col="blue4", xlab="Months",ylab="SO2 (µg/m^3)",main="SO2 concentrations over the months")
plot(data$hour, data$SO2, col="blue4", xlab="Hours",ylab="SO2 (µg/m^3)",main="SO2 concentrations over the Hours")
plot(data$year, data$SO2, col="blue4", xlab="Year", ylab="SO2(µg/m^3)", main="SO2 concentration each year")

#check frequency of values
hist(data$SO2, breaks = sqrt(nrow(data)), xlab="SO2 (µg/m^3)", main = "Frequency Distribution of SO2 Concentration" , col=viridis(sqrt(nrow(data))))

```

##NO2
```{r}
#summary stats
summary(data$NO2)
#outliers
boxplot(data$NO2,ylab = "mu g/m^3")
#plot values over time variables
plot(data$month, data$NO2, col="blue4", xlab="Months",ylab="NO2 (µg/m^3)",main="NO2 concentrations by Month")
plot(data$hour, data$NO2, col="blue4", xlab="Hours",ylab="NO2 (µg/m^3)",main="NO2 concentrations over the Hours")
plot(data$year, data$NO2, col="blue4", xlab="Year", ylab="NO2(µg/m^3)", main="NO2 concentration each year")

#frequency of values
hist(data$NO2, breaks = sqrt(nrow(data)), xlab="NO2 (µg/m^3)", main = "Frequency Distribution of NO2 Concentration" , col=viridis(sqrt(nrow(data))))
```

##CO
```{r}
#summary stats
summary(data$CO)
#outliers
boxplot(data$CO,ylab = "mu g/m^3")
#plot values over time variables
plot(data$month, data$CO, col="blue4", xlab="Months",ylab="CO (µg/m^3)",main="CO concentrations by Month")
plot(data$hour, data$CO, col="blue4", xlab="Hours",ylab="Co (µg/m^3)",main="CO concentrations over the Hours")
plot(data$year, data$CO, col="blue4", xlab="Year", ylab="CO (µg/m^3)", main="CO concentration each year")
#check frequency of values
hist(data$CO, breaks = sqrt(nrow(data)), xlab="CO (µg/m^3)", main = "Frequency Distribution of CO Concentration" , col=viridis(sqrt(nrow(data))))
```

##O3
```{r}
#summary statistics
summary(data$O3)
#outliers
boxplot(data$O3,ylab = "mu g/m^3")

#plot values over time variables
plot(data$month, data$O3, col="blue4", xlab="Months",ylab="O3 (µg/m^3)",main="O3 concentrations by Month")
plot(data$hour, data$O3, col="blue4", xlab="Hours",ylab="O3 (µg/m^3)",main="O3 concentrations over the Hours")
plot(data$year, data$O3, col="blue4", xlab="Year", ylab="O3 (µg/m^3)", main="O3 concentration each year")

#frequency of values
hist(data$O3, breaks = sqrt(nrow(data)), xlab="O3 (µg/m^3)", main = "Frequency Distribution of O3 Concentration" , col=viridis(sqrt(nrow(data))))

```

##Temperature
```{r}
#summery statistics
summary(data$TEMP)
#outlines
boxplot(data$TEMP)

#plot values over time variables
plot(data$month, data$TEMP, col="blue4", xlab="Months",ylab="Temperature (°C) ",main="Temperature By Month")
plot(data$hour, data$TEMP, col="blue4", xlab="Hours",ylab="Temperature",main="Temperature over the Hours")

#distribution of values
hist(data$TEMP, breaks = sqrt(nrow(data)), xlab="Temperature (°C)", main = "Frequency Distribution of Temperature" , col=viridis(sqrt(nrow(data))))
```

##Pressure
```{r}
#pressure
#Summary statistics
summary(data$PRES)
#outliers
boxplot(data$PRES)

#plot values over time variables
plot(data$month, data$PRES, col="blue4", xlab="Months",ylab="Pressure (hPa) ",main="Pressure Change by Month")
plot(data$hour, data$PRES, col="blue4", xlab="Hours",ylab="Pressure (hPa)",main="Pressure change by Hour")  #not much change in hour by hour data

#distribution of values
hist(data$PRES, breaks = sqrt(nrow(data)), xlab="Pressure (hPa)", main = "Frequency Distribution of Pressure" , col=viridis(sqrt(nrow(data))))
```



##Dew Point
```{r}
#summary stats
summary(data$DEWP)
#outliers
boxplot(data$DEWP)

#plot values over time variables
plot(data$month, data$DEWP, col="blue4", xlab="Months",ylab="Dew Point (°C)",main="Dew Point by Month")
plot(data$hour, data$DEWP, col="blue4", xlab="Hours",ylab="Dew Point",main="Dew Point by Hour")  #not really any changes 

#distribution of values
hist(data$DEWP, breaks = sqrt(nrow(data)), xlab="Dew Point (°C)", main = "Frequency Distribution of Dew Point" , col=viridis(sqrt(nrow(data))))
```

##Rain
```{r}
#summary statistics
summary(data$RAIN)
#outliers
boxplot(data$RAIN)

#plot values over time variables
plot(data$month, data$RAIN, col="blue4", xlab="Months",ylab="Rain (mm)",main="Precipitation by Month")
plot(data$hour, data$RAIN, col="blue4", xlab="Hours",ylab="Rain (mm)",main="Precipitation level by Hour")   
plot(data$year, data$RAIN, col="blue4", xlab="Hours",ylab="Rain (mm)",main="Precipitation level by Year")

#distribution
hist(data$RAIN, breaks = sqrt(nrow(data)), xlab="Rain (mm)", main = "Frequency Distribution of Rain" , col=viridis(sqrt(nrow(data))))
```

##Wind Direction
```{r}
summary(data$wd)

#already have package installed
#load package
library('dplyr')

#count the number of values per wind direction 
count_vals <- count(data, vars= wd)
names(count_vals) <- c("Wind Direction", "Total Number")

count_vals

directions <- c("E","ENE","ESE","N","NE", "NNE","NNW","NW","S","SE", "SSE","SSW","SW","W","WNW","WSW","NA")

colours <- c("")
  
barplot(count_vals$`Total Number`, names.arg = directions , col = viridis(17), main = "Frequency of Wind Direction")

#group values into 4 major directions 

east <- sum(count_vals[1:3,2])
north <- sum(count_vals[7:8,2])
south <- sum(count_vals[9:13,2])
west <- sum(count_vals[14:16,2])

NESW <- c(east, north, south, west)

barplot(NESW, names = c("East","North","South","West"), col = viridis(4), main = "Frequency of Wind Direction")

```


##Wind Speed
```{r}
#summary statistics
summary(data$WSPM)
#boxplot for outliers
boxplot(data$WSPM)

#plot values over time variables
plot(data$month, data$WSPM, col="blue4", xlab="Months",ylab="Wind Speed (m/s)",main="Wind speed by Month")
plot(data$hour, data$WSPM, col="blue4", xlab="Hours",ylab="Wind Speed (m/s)",main="Wind Speed by Hour")   
plot(data$year, data$WSPM, col="blue4", xlab="Hours",ylab="Wind Speed (m/s)",main="Wind Speed by Year")

#check distribution
hist(data$WSPM, breaks = sqrt(nrow(data)), xlab = "Wind Speed (m/s)", main = "Frequency Distribution of Wind Speed", col=viridis(sqrt(nrow(data))))
```
```{r}
#install.packages("psych")
library(psych)

#create a summary table of all values 
describe(data, fast = TRUE)

#gives column number, number of valid cases, mean value,max and min values, the range and standard error


```
```{r}
#create another summary table grouped by year
#only looking at rows 6 to 17, ignoring station and time values 
describeBy(data[,6:17],group=data$year, fast = TRUE)
```

```{r}

```

